// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGrhzXen9Dmly2gVAF0ZD-7wS4ArxxkUY',
    appId: '1:663286077131:web:6e0f147eebd43181d8ed4e',
    messagingSenderId: '663286077131',
    projectId: 'ams-app-project',
    authDomain: 'ams-app-project.firebaseapp.com',
    storageBucket: 'ams-app-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5DxKoVaecMds7QCDYKPasNaHxmfTmGGs',
    appId: '1:663286077131:android:d71dacc51f00259ed8ed4e',
    messagingSenderId: '663286077131',
    projectId: 'ams-app-project',
    storageBucket: 'ams-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBvWCTHJBSlYCErIOBSPLV6xIpEJtdFYM',
    appId: '1:663286077131:ios:b38a9c52550efb90d8ed4e',
    messagingSenderId: '663286077131',
    projectId: 'ams-app-project',
    storageBucket: 'ams-app-project.appspot.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBvWCTHJBSlYCErIOBSPLV6xIpEJtdFYM',
    appId: '1:663286077131:ios:0c26a8640c4b39d1d8ed4e',
    messagingSenderId: '663286077131',
    projectId: 'ams-app-project',
    storageBucket: 'ams-app-project.appspot.com',
    iosBundleId: 'com.example.ams.RunnerTests',
  );
}
